version: '2.1'
services:

  blockchain:
    container_name: blockchain-fundamentals
    build:
      context: .
      dockerfile: Dockerfile
    image:
      rodders1991/blockchain-fundamentals
    ports:
      - "3000:3000"
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      - APP_NAME=blockchain-fundamentals
      - MONGO_URI=mongodb://mongodb/${APP_NAME}
    command: npm run blockchain:init -- -d5

  mongodb:
      image: mongo:latest
      container_name: "mongodb"
      volumes:
        - ./data/db:/data/db
      environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
      command: mongod --smallfiles --logpath=/dev/null # --quiet
